Use MSAL instead of IdentityModel for token generation
FHIDev/Fhi.ClientCredentials pull request #88
Opened 2024-10-08 15:05 UTC by martinmine

2024-10-16 15:17 UTC, OsirisTerje requested changes

2024-10-16 15:17 UTC, OsirisTerje commented on ClientCredentialsKeypairs/Constants.cs
> +    public const string DPoP = "DPoP";
Bruk nameof
Flere under også

2024-10-16 15:17 UTC, OsirisTerje commented on ClientCredentialsKeypairs/AuthenticationService.cs
> +                        throw new Exception("There must be exactly one value for the DPoP-Nonce header");
```suggestion
                        throw new DPoPException("There must be exactly one value for the DPoP-Nonce header");
```

Lag egen exception, don't throw base class Exception

2024-10-16 15:17 UTC, OsirisTerje commented on Fhi.ClientCredentialsKeypairs.Tests/Mocks/OauthTestServerHandler.cs
> +            return CreateResult(new TokenResponse { AccessToken = "BearerToken", TokenType = "Bearer"});
```suggestion
            return CreateResult(new TokenResponse { AccessToken = "BearerToken", TokenType = AuthenticationScheme.Bearer});
```

2024-10-21 08:14 UTC, martinmine commented on ClientCredentialsKeypairs/Constants.cs
> +    public const string DPoP = "DPoP";
Dersom det hadde vært en property som vi selv styrer hadde det vært nice å bruke `nameof`, her er vi derimot avhengig av hva RFC9449 sier og da tenker jeg det gir mer mening å bruke en const på denne måten her.

2024-10-28 15:03 UTC, OsirisTerje approved these changes

2024-10-28 15:04 UTC, merged